repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: unittest
        name: Run unittest
        entry: python -m unittest discover -s test/unittest/
        language: system
        pass_filenames: false
        always_run: true
